Building DAG of jobs...
InputFunctionException in rule soapnuke in file /home/liuxin/data_pasteur/12_epigenome/WGBS/snakefile.py, line 31:
Error:
  KeyError: "None of [Index(['sample1'], dtype='object')] are in the [index]"
Wildcards:
  sample=sample1
Traceback:
  File "/home/liuxin/data_pasteur/12_epigenome/WGBS/snakefile.py", line 33, in <lambda>
  File "/home/liuxin/data_pasteur/12_epigenome/WGBS/snakefile.py", line 15, in get_reads
  File "/home/liuxin/mambaforge/envs/snakemake/lib/python3.9/site-packages/pandas/core/indexing.py", line 1097, in __getitem__
  File "/home/liuxin/mambaforge/envs/snakemake/lib/python3.9/site-packages/pandas/core/indexing.py", line 1280, in _getitem_tuple
  File "/home/liuxin/mambaforge/envs/snakemake/lib/python3.9/site-packages/pandas/core/indexing.py", line 1024, in _getitem_lowerdim
  File "/home/liuxin/mambaforge/envs/snakemake/lib/python3.9/site-packages/pandas/core/indexing.py", line 1103, in __getitem__
  File "/home/liuxin/mambaforge/envs/snakemake/lib/python3.9/site-packages/pandas/core/indexing.py", line 1332, in _getitem_axis
  File "/home/liuxin/mambaforge/envs/snakemake/lib/python3.9/site-packages/pandas/core/indexing.py", line 1272, in _getitem_iterable
  File "/home/liuxin/mambaforge/envs/snakemake/lib/python3.9/site-packages/pandas/core/indexing.py", line 1462, in _get_listlike_indexer
  File "/home/liuxin/mambaforge/envs/snakemake/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5877, in _get_indexer_strict
  File "/home/liuxin/mambaforge/envs/snakemake/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5938, in _raise_if_missing
